receivers:
  jaeger:
    protocols:
      thrift_http:
        endpoint: "0.0.0.0:14278" # port opened on the otel collector

  # Dummy receiver that's never used, because a pipeline is required to have one.
  otlp/spanmetrics:
    protocols:
      grpc:
        endpoint: "localhost:65535"

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

  otlphttp/openobserve:
    endpoint: http://openobserve:5080/api/default/
    headers:
      Authorization: Basic aml0ZW5AZXhhbXBsZS5jb206aml0ZW5AMTIzCg==
      stream-name: default

  otlp/jaeger: # Jaeger supports OTLP directly. The default port for OTLP/gRPC is 4317
    endpoint: "jaeger:4317"
    tls:
      insecure: true

processors:
  batch:
  # spanmetrics:
  #   metrics_exporter: prometheus

service:
  pipelines:
    traces:
      receivers: [jaeger]
      processors: []
      exporters: [otlp/jaeger, otlphttp/openobserve]
    # The exporter name in this pipeline must match the spanmetrics.metrics_exporter name.
    # The receiver is just a dummy and never used; added to pass validation requiring at least one receiver in a pipeline.
    # metrics/spanmetrics:
    #   receivers: [otlp/spanmetrics]
    #   exporters: [prometheus]